apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration-job
spec:
  template:
    spec:
      containers:
        - name: alembic-migration
          image: local:image
          command: ["alembic", "upgrade", "head"]
          env:
            - name: API_PORT
              value: "80"
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_URL
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_USERNAME
      restartPolicy: OnFailure
