apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration-job
spec:
  template:
    spec:
      containers:
        - name: alembic-migration
          image: local:image
          command: ["alembic", "upgrade", "head"]
          env:
            - name: API_PORT
              value: "80"
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_URI
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_URL
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_PORT
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_PASSWORD
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_DATABASE
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_URL
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_URI
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_URI
      restartPolicy: OnFailure
