apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-soat
  labels:
    app: fiap-soat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-soat
  template:
    metadata:
      labels:
        app: fiap-soat
    spec:
      containers:
        - name: fiap-soat
          image: alceuramos/dev:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: API_PORT
              value: "80"
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_URL
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_PASSWORD
      imagePullSecrets:
        - name: dockerhub-secret
