apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiap-soad-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fiap-soad.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fiap-soad-service
            port:
              number: 80
